---
- name: Check if directory exists for .bash_profile
  stat:
    path: /home/circleci
  register: bash_profile_directory_exists

- name: Create directory for .bash_profile if it doesn't exist
  file:
    path: /home/circleci
    state: directory
  when: not bash_profile_directory_exists.stat.exists

- name: Check if .bash_profile exists
  stat:
    path: /home/circleci/.bash_profile
  register: bash_profile_exists

- name: Create .bash_profile if it doesn't exist
  file:
    path: /home/circleci/.bash_profile
    state: touch
  when: not bash_profile_exists.stat.exists

- name: Add rbenv to PATH in .bash_profile
  lineinfile: 
    path: /home/circleci/.bash_profile
    line: 'export PATH="$HOME/.rbenv/bin:$PATH"'
  when: bash_profile_exists.stat.exists

- name: install rbenv
  become: yes
  git: 
    repo: https://github.com/sstephenson/rbenv.git 
    dest: /home/circleci/.rbenv

- name: edit permission rbenv
  become: yes
  file:
    path: /home/circleci/.rbenv
    state: directory
    owner: circleci
    group: circleci

- name: Add rbenv to PATH
  lineinfile: 
    path: /home/circleci/.bash_profile
    line: 'export PATH="$HOME/.rbenv/bin:$PATH"'

- name: eval rbenv init
  lineinfile: 
    path: /home/circleci/.bash_profile
    line: 'eval "$(rbenv init -)"'

- name: rbenv setting
  shell: bash -lc "source ~/.bash_profile"

#ruby-buildのインストール 
- name: install ruby-build
  git:
    repo: https://github.com/sstephenson/ruby-build.git
    dest: /home/circleci/.rbenv/plugins/ruby-build

#ruby install 確認
- name: check ruby installed
  stat:
    path: /home/circleci/.rbenv/bin/
  register: ruby_installed

- name: Install dependencies
  become: true
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - git
    - gcc
    - bzip2
    - openssl-devel
    - libyaml-devel
    - libffi-devel
    - readline-devel
    - zlib-devel
    - gdbm-devel
    - ncurses-devel

#rubyのインストール
- name: Install Ruby 3.1.2
  become: yes
  become_user: circleci
  shell: |
    /home/circleci/.rbenv/bin/rbenv install 3.1.2
    /home/circleci/.rbenv/bin/rbenv global 3.1.2
    /home/circleci/.rbenv/bin/rbenv rehash
  when: not ruby_installed.stat.exists

#rubyを使用可能にする
- name: set default ruby version rehash
  become_user: circleci
  shell: bash -lc "rbenv rehash"

#インスタンスで使用するバージョンの設定
- name: set default ruby version
  become_user: circleci
  shell: bash -lc "rbenv global 3.1.2"

