# rbenvインストール
- name: install rbenv
  become: true
  git: 
    repo: https://github.com/sstephenson/rbenv.git 
    dest: /home/ec2-user/.rbenv

- name: edit permission rbenv
  become: true
  file:
    path: /home/ec2-user/.rbenv
    state: directory
    owner: ec2-user
    group: ec2-user

# パスを通す
- name: Add rbenv to PATH
  lineinfile: 
    path: /home/ec2-user/.bash_profile
    line: 'export PATH="$HOME/.rbenv/bin:$PATH"'

- name: eval rbenv init
  lineinfile: 
    path: /home/ec2-user/.bash_profile
    line: 'eval "$(rbenv init -)"'

- name: rbenv setting
  shell: bash -lc "source ~/.bash_profile"

# ruby-buildのインストール 
- name: install ruby-build
  git:
    repo: https://github.com/sstephenson/ruby-build.git
    dest: /home/ec2-user/.rbenv/plugins/ruby-build
  become: true

# openssl-develのインストール
- name: install openssl-devel
  become: true
  yum:
    name: openssl-devel
    state: present

# rubyのインストール
- name: install ruby
  vars:
    ruby_version: 3.2.2
  become: yes
  become_user: ec2-user
  shell: bash -lc "rbenv install {{ ruby_version }} && rbenv global {{ ruby_version }} && rbenv rehash"

- name: set default ruby version rehash
  become_user: ec2-user
  shell: bash -lc "rbenv rehash"

- name: set default ruby version
  become_user: ec2-user
  shell: bash -lc "rbenv global {{ ruby_version }}"

- name: install bundler
  become_user: ec2-user
  shell: bash -lc "gem install bundler -v {{ bundler_version }}"

# railsインストール
- name: install rails
  become_user: ec2-user
  shell: bash -lc "gem install rails -v {{ rails_version }}"
