- name: Check app installed
  stat:
    path: /home/circleci/raisetech-live8-sample-app
  register: app_installed

- name: Set directory permissions
  ansible.builtin.file:
    path: /home/circleci/raisetech-live8-sample-app
    state: directory
    owner: ec2-user  # 適切な所有者に変更する
    group: ec2-user  # 適切なグループに変更する
    mode: '0755'    

# サンプルアプリケーションをclone
- name: Git clone sample app
  become_user: ec2-user
  ansible.builtin.git:
    repo: https://github.com/yuta-ushijima/raisetech-live8-sample-app.git
    dest: /home/circleci/raisetech-live8-sample-app
  when: not app_installed.stat.exists


- name: current directory
  shell: pwd
  register: current_dir_output
  changed_when: false

- name: Display current directory
  debug:
    var: current_dir_output.stdout

- name: bundle install
  shell: "/usr/bin/env bash -lc 'cd /home/circleci/raisetech-live8-sample-app/ && /home/circleci/.rbenv/bin/rbenv exec bundle install'"
  environment:
    PATH: "/home/circleci/.rbenv/bin:$PATH"
