- name: Check app installed
  stat:
    path: /home/circleci/raisetech-live8-sample-app
  register: app_installed

- name: Set directory permissions
  ansible.builtin.file:
    path: /home/circleci/raisetech-live8-sample-app
    state: directory
    owner: ec2-user  # 適切な所有者に変更する
    group: ec2-user  # 適切なグループに変更する
    mode: '0755'    

# サンプルアプリケーションをclone
- name: Git clone sample app
  become_user: ec2-user
  ansible.builtin.git:
    repo: https://github.com/yuta-ushijima/raisetech-live8-sample-app.git
    dest: /home/circleci/raisetech-live8-sample-app
  when: not app_installed.stat.exists

- name: Upgrade Ruby to version 3.1.2
  become_user: ec2-user
  ansible.builtin.command: rbenv install 3.1.2
  when: not ruby_installed.stat.exists

- name: Set global Ruby version to 3.1.2
  become_user: ec2-user
  ansible.builtin.command: rbenv global 3.1.2
  when: not ruby_installed.stat.exists

- name: Reload rbenv
  become_user: ec2-user
  ansible.builtin.command: rbenv rehash
  when: not ruby_installed.stat.exists

- name: Install bundler gem
  become_user: ec2-user
  ansible.builtin.command: sudo gem install bundler -v 2.4.18

# unicornインストール
- name: bundle install
  shell: bash -lc "bundle install"
  args: 
    chdir: /home/circleci/raisetech-live8-sample-app/